### ISSUE TITLE
no information of BabelMorphWord

### ISSUE THREAD

**Issue by eveliao** [raganato/BabelMorph#1]
I ran Example.java. But the output is

> Lemma	Lang	PoS	inflected forms
eat	EN	verb	ate info:[no-info]	eats info:[no-info]	eating info:[no-info]	eaten info:[no-info]	et info:[no-info]

There is no specific information of inflected forms, such as present, past participate.

But I need the information. How can I get it? Should I update the index files myself?

**Comment by raganato** [comment]
i've updated the project with a new index with the data from the UniMorph project. 
The available information depend from the UniMorph project.

**Comment by eveliao** [comment]
I downloaded the latest version of BabelMorph.  However the directory that should contain the data file is empty.

> INFO: Opening index: path/to/indexFolder
Exception in thread "main" java.lang.RuntimeException: Could not init BabelMorph: no segments* file found in SimpleFSDirectory@\BabelMorph\path\to\indexFolder lockFactory=org.apache.lucene.store.NativeFSLockFactory@2d8e6db6: files: []
	at it.uniroma1.lcl.babelmorph.BabelMorph.getInstance(BabelMorph.java:90)
	at it.uniroma1.lcl.babelmorph.example.Example.main(Example.java:21)

**Comment by raganato** [comment]
you need to download the index, extract it, and configure the file located inside the config folder (babelmorph.properties) with the path to the index folder.
From the error it seems that it's trying still to open the fake path "\path\to\indexFolder" in the babelmorph.properties file.
